# Generated by Django 6.0 on 2026-01-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='experience',
            field=models.CharField(default='0 years', help_text='e.g. 5 years', max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='pricing',
            field=models.CharField(default='Negotiable', help_text='e.g. $50/hr', max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_category', to='services.service'),
        ),
    ]
