# Generated by Django 6.0 on 2026-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_providerprofile_experience_providerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Contact number', max_length=20),
        ),
    ]
