# Generated by Django 6.0 on 2026-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_providerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Full address', max_length=255),
        ),
    ]
