# Generated by Django 6.0 on 2026-01-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_providerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='district',
            field=models.CharField(blank=True, default='', help_text='District', max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='pincode',
            field=models.CharField(blank=True, default='', help_text='Pincode', max_length=10),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='post_office',
            field=models.CharField(blank=True, default='', help_text='Post Office', max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State', max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='village_or_area',
            field=models.CharField(blank=True, default='', help_text='Village or Area name', max_length=255),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='address',
            field=models.CharField(blank=True, default='', help_text='House No, Street, or Colony', max_length=255),
        ),
    ]
